[package]
name = "canager"
version = "0.1.0"
description = "A friendly manager for everything you installed from the terminal"
authors = ["Brulek"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "canager_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2.11.1", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-updater = "2.11.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
canager-core = { path = "../crates/canager-core" }
fix-path-env = { git = "https://github.com/tauri-apps/fix-path-env-rs" }


# Read the optimization guideline for more details: https://tauri.app/concept/size/#cargo-configuration
[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
